// 入力: 応答や指示から一言に出す1行を取り出す。

/**
 * 最後の応答の冒頭(PRODUCT.md「一覧の表示」)。
 * 空行、コードの囲み(中身を含む)、表の行、区切り線を飛ばし、見出し・強調・箇条書き・番号・引用の記号とバッククォートを除く。
 * 飛ばすと何も残らないときは、囲みの中の1行目を出す。
 */
export function leadLine(text: string): string | undefined {
  let inFence = false;
  let fenceFirst: string | undefined;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (/^(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) {
      if (fenceFirst === undefined && line !== '') fenceFirst = line;
      continue;
    }
    if (line === '') continue;
    if (line.startsWith('|')) continue;
    if (/^([-*_])(\s*\1){2,}$/.test(line)) continue;
    const cleaned = stripMarks(line);
    if (cleaned !== '') return cleaned;
  }
  return fenceFirst;
}

function stripMarks(line: string): string {
  let s = line;
  for (;;) {
    const before = s;
    s = s
      .replace(/^#{1,6}\s+/, '')
      .replace(/^>\s?/, '')
      .replace(/^[-*+]\s+/, '')
      .replace(/^\d+[.)]\s+/, '')
      .replace(/^\[[ xX]\]\s+/, '');
    if (s === before) break;
  }
  s = s.replace(/\*\*|__|~~/g, '');
  s = s.replace(/(^|[^\w*])\*(?=\S)([^*]*?\S)\*(?![\w*])/g, '$1$2');
  s = s.replace(/(^|[^\w])_(?=\S)([^_]*?\S)_(?!\w)/g, '$1$2');
  s = s.replace(/`/g, '');
  return s.trim();
}

/** 指示の1行目(空行を飛ばす)。 */
export function firstLine(text: string): string | undefined {
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line !== '') return line;
  }
  return undefined;
}

/** 道具と対象(`Bash: <コマンド>`、`Edit: <ファイル>`)。 */
export function toolTarget(name: string, input: unknown): string {
  const o = (input && typeof input === 'object' ? input : {}) as Record<string, unknown>;
  const pick = (...keys: string[]) => {
    for (const k of keys) {
      const v = o[k];
      if (typeof v === 'string' && v !== '') return v;
    }
    return undefined;
  };
  const target =
    pick(
      'command',
      'file_path',
      'notebook_path',
      'path',
      'url',
      'pattern',
      'query',
      'skill',
      'description',
      'prompt',
    ) ?? '';
  const one = firstLine(target) ?? '';
  return one ? `${name}: ${one}` : name;
}

/** 会話記録の利用者の行の本文を、指示として扱うときの文字列にする。指示でなければ undefined。 */
export function instructionText(content: string): string | undefined {
  const t = content.trimStart();
  // ターンを始めるコマンド(スキルの呼び出しなど)は `<command-message>` で始まる。
  // 手元で完結するコマンド(`/model`、`/exit` など)は `<command-name>` で始まり、指示に数えない。
  if (t.startsWith('<command-message>')) {
    const name = /<command-name>\s*([^<]*?)\s*<\/command-name>/.exec(t)?.[1];
    const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(t)?.[1]?.trim();
    if (!name) return undefined;
    const n = name.startsWith('/') ? name : `/${name}`;
    return args ? `${n} ${args}` : n;
  }
  if (/^<(command-name|local-command-|bash-input|bash-stdout|bash-stderr|system-reminder|task-notification)/.test(t))
    return undefined;
  if (t.startsWith('Caveat: The messages below were generated by the user while running local commands'))
    return undefined;
  return firstLine(content);
}
